apiVersion: v1
kind: Pod
metadata:
  name: parsec-libxml2
  labels:
    app: libxml2
spec:
  containers:
  - name: libxml2
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "parsec.libxml2", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure