apiVersion: v1
kind: Pod
metadata:
  name: parsec-swaptions
  labels:
    app: swaptions
spec:
  containers:
  - name: swaptions
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "parsec.swaptions", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure