apiVersion: v1
kind: Pod
metadata:
  name: parsec-facesim 
  labels:
    app: facesim 
spec:
  containers:
  - name: facesim 
    image: spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "parsec.facesim ", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure