apiVersion: v1
kind: Pod
metadata:
  name: parsec-netstreamcluster
  labels:
    app: netstreamcluster
spec:
  containers:
  - name: netstreamcluster
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "parsec.netstreamcluster", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure