apiVersion: v1
kind: Pod
metadata:
  name: splash2-ocean_ncp
  labels:
    app: ocean_ncp
spec:
  containers:
  - name: ocean_ncp
    image: spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.ocean_ncp", "-i", "native"]    
    resources:
      requests:
        memory: 2000Mi
      limits:
        memory: 8000Mi