apiVersion: v1
kind: Pod
metadata:
  name: splash2-cholesky
  labels:
    app: cholesky
spec:
  containers:
  - name: cholesky
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.cholesky", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure