apiVersion: v1
kind: Pod
metadata:
  name: splash2-ocean-ncp
  labels:
    app: ocean-ncp
spec:
  containers:
  - name: ocean-ncp
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.ocean_ncp", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure