apiVersion: v1
kind: Pod
metadata:
  name: splash2-water-spatial
  labels:
    app: water-spatial
spec:
  containers:
  - name: water-spatial
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.water_spatial", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure