apiVersion: v1
kind: Pod
metadata:
  name: splash2-volrend
  labels:
    app: volrend
spec:
  containers:
  - name: volrend
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.volrend", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure