apiVersion: v1
kind: Pod
metadata:
  name: splash2-fmm
  labels:
    app: fmm
spec:
  containers:
  - name: fmm
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.fmm", "-i", "simlarge"] 
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure
