apiVersion: v1
kind: Pod
metadata:
  name: splash2-raytrace
  labels:
    app: raytrace
spec:
  containers:
  - name: raytrace
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.raytrace", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure