apiVersion: v1
kind: Pod
metadata:
  name: splash2x-ocean-cp
  labels:
    app: ocean-cp
spec:
  containers:
  - name: ocean-cp
    image: spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2x.ocean_cp", "-i", "native"]    
    resources:
      requests:
        memory: 2000Mi
      limits:
        memory: 8000Mi