apiVersion: v1
kind: Pod
metadata:
  name: splash2-lu-ncb
  labels:
    app: lu-ncb
spec:
  containers:
  - name: lu-ncb
    image: docker.io/spirals/parsec-3.0:latest
    imagePullPolicy: IfNotPresent    
    args: ["-a", "run", "-p", "splash2.lu_ncb", "-i", "native"]    
    resources:
      requests:
        memory: 10000Mi
      limits:
        memory: 16000Mi
  restartPolicy: OnFailure