apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: docker.io/nginx
    imagePullPolicy: IfNotPresent    
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 160Mi
        cpu: 200m
  restartPolicy: OnFailure